- uses: actions/checkout@v3
  with:
    fetch-depth: 0          # ① 完整克隆，才能更新远端引用

- name: Sync & push to Pavlovia
  env:
    USERNAME: ${{ secrets.PAVLOVIA_USER }}
    TOKEN:    ${{ secrets.PAVLOVIA_PAT }}
  run: |
    git remote add pav "https://${USERNAME}:${TOKEN}@gitlab.pavlovia.org/${USERNAME}/baba_js_version.git"
    
    # ② 先获取远端最新 commit，刷新 refs
    git fetch pav main
    
    # ③ 覆盖推送，但加 --force-with-lease（只在远端没新提交时覆盖）
    git push pav HEAD:main --force-with-lease
